name: Publish Docs

on:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  publish:
    permissions:
      contents: read
      pages: write
      id-token: write

    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Build docs
        id: build
        run: |
          forge doc --build

      - name: Upload Artifact
        id: publish
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs/book"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
